# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user_list = [
  {username: "pauliec", email: "pcherian10@gmail.com", password: "123"},
  {username: "mariac", email: "maria.cherian@gmail.com", password: "123"},
  {username: "tcherian", email: "tcherian@manh.com", password: "123"},
  {username: "paul", email: "pcherian@gmail.com", password: "123"},
  {username: "lebronny", email: "lebronjames@lakers.com", password: "123"},
  {username: "ladySquirrelly", email: "rubes.melissa@gmail.com", password: "123"},
  {username: "willferrell", email: "willferrell@gmail.com", password: "123"}
]

question_list =[
  {question_text:"What area of the baseball field typically contains the greatest number of fielders?",
    author_id: 2,
    first_choice: "Infield",
    second_choice: "Outfield",
    third_choice: "Pitcher's mount",
    correct_answer: 1 },
  {question_text:"In club soccer, the period of time where players are allowed to change teams is called what?",
    author_id: 4,
    first_choice: "Trade deadline",
    second_choice: "Transfer window",
    third_choice: "Superdraft",
    correct_answer: 1 },
  {question_text:"What NFL team won the greatest number of shutouts in a single postseason?",
    author_id: 5,
    first_choice: "Chicago Bears",
    second_choice: "Baltimore Ravens",
    third_choice: "Pittsburgh Steelers",
    correct_answer: 1 },
  {question_text:"Before James Harden, who was the last NBA MVP to primarily shoot left-handed?",
    author_id: 6,
    first_choice: "Steve Nash",
    second_choice: "David Robinson",
    third_choice: "Charles Barkley",
    correct_answer: 2 },
  {question_text:"A mistakenly released Taylor Swift track, which hit No. 1 on iTunes Canada, was eight seconds of what?",
    author_id: 7,
    first_choice: "Water running",
    second_choice: "Humming",
    third_choice: "White noise",
    correct_answer: 3},
  {question_text:"The country that comes first alphabetically is located on what continent?",
    author_id: 1,
    first_choice: "Europe",
    second_choice: "Africa",
    third_choice: "Asia",
    correct_answer: 3},
  {question_text:"Which of these Jane Austen characters was introduced first?",
    author_id: 2,
    first_choice: "Elinor Dashwood",
    second_choice: "Elizabeth Bennet",
    third_choice: "Emma Woodhouse",
    correct_answer: 1 },
  {question_text:"The three-minute-long tracking shot in “Goodfellas” ends on what legendary comedian?",
    author_id: 3,
    first_choice: "Jack Benny",
    second_choice: "Don Rickles",
    third_choice: "Henny Youngman",
    correct_answer: 3 },
  {question_text:"In 1986, dozens of new animal species were discovered in a cave sealed off from the world in what country?",
    author_id: 4,
    first_choice: "Romania",
    second_choice: "Ukraine",
    third_choice: "Moldova",
    correct_answer: 1 },
  {question_text:"'I know it was you, Fredo' is a line from what classic mafia movie sequel?",
    author_id: 5,
    first_choice: "The Godfather: Part II",
    second_choice: "Grease 2",
    third_choice: "Speed 2: Cruise Control",
    correct_answer: 1 },
  {question_text:"In “To All the Boys I’ve Loved Before,” what gets sent to all the boys?",
    author_id: 6,
    first_choice: "Letters",
    second_choice: "Fyre Festival Tickets",
    third_choice: "HQ Extra Lives",
    correct_answer: 1 },
  {question_text:"What does Dorothy have to do with her ruby slippers in order to go home?",
    author_id: 7,
    first_choice: "Take them off",
    second_choice: "Tap them together",
    third_choice: "Put them in water",
    correct_answer: 2 },
  {question_text:"The hit biopic “Straight Outta Compton” is based on what music group?",
    author_id: 1,
    first_choice: "Wu-Tang Clan",
    second_choice: "Fugees",
    third_choice: "NWA",
    correct_answer: 3 },
  {question_text:"Jim Carrey became the first actor to make $20 million per movie for what film?",
    author_id: 2,
    first_choice: "Bruce Almighty",
    second_choice: "The Mask",
    third_choice: "The Cable Guy",
    correct_answer: 3 },
  {question_text:"Which of these romantic movies does NOT have a dramatic airport scene?",
    author_id: 3,
    first_choice: "Garden State",
    second_choice: "Love Actually",
    third_choice: "Maid in Manhattan",
    correct_answer: 3},
  {question_text:"What is the response after Indiana Jones first asks, “Snakes, why’d it have to be snakes?”",
    author_id: 4,
    first_choice: "Good luck, Dr.Jones",
    second_choice: "Try charming them",
    third_choice: "Asps! Very dangerous",
    correct_answer: 3 },
  {question_text:"Which of these on-screen Batmans has also played a fictional US president in a movie?",
    author_id: 5,
    first_choice: "Val Kilmer",
    second_choice: "Christian Bale",
    third_choice: "Michael Keaton",
    correct_answer: 3},
  {question_text:"In which film did Marilyn Monroe portray a ukulele player?",
    author_id: 6,
    first_choice: "Some Like It Hot",
    second_choice: "Gentlemen Prefer Blondes",
    third_choice: "The Seven Year Itch",
    correct_answer: 1},
  {question_text:"Which of these is one of the aliases of the lead hacker in “Hackers”?",
    author_id: 7,
    first_choice: "The Plague",
    second_choice: "Crash Override",
    third_choice: "Phantom Phreak",
    correct_answer: 1 }
]

user_list.each do |u|
  User.create(u)
end

question_list.each do |q|
  Question.create(q)
end



